# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PalmMedia - Social Media, Podcasting, Content Distribution
description: We specialize in making effective social media marketing campaigns, podcast distribution, content production and business branding
keywords: agency, social media marketing, marketing, podcasting, podcast, podcast production, podcast distribution, content production, prague, website development, facebook ads, instagram ads, styvekdrtic, Jiri Stepanek
author: palmmedia.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://palmmedia.co/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
